[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/product"
  to = "/.netlify/functions/product"
  status = 200

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
